### PR TITLE
UI/UX design changes

### PR DESCRIPTION
**Pull request by weiw11**
Also a minor fix for the margin on tabs and table.

Current:
image

Changes:
image

### CODE REVIEW

**Comment by weiw11** [comment]
The only changes were to the styling. I had to adjust the tabbing since some of them were a bit off and was making editing a bit difficult as code collapse didn't work on VS Code.

**Comment by Silberdrachi** [comment]
Hmm i was tinkering with the current bars in my 1.0 update which will likely break this PR. As the 1.0 update is going to be going live in about 3h (from now) i am going to hold off on merging this PR to see what it looks like after all the 1.0 updates are merged.

Most of what i changed was breaking the 2 current rows up into 2 groups of 2 rows. Though to be honest i wasnt happy with its performance on some window sizes.

**Comment by weiw11** [comment]
Ah I see. I didn't realize you're working on it as well haha. But my implementation is something similar as well, see the gif below. The current implementation with col-row-col is quite buggy which is why I changed it to container-row-col.

This is how my current changes works at different resolutions/devices.

**Comment by Silberdrachi** [comment]
ive obviously pushed the changes i made for 1.0, so you can see what i did to 'fix it' 

i think chances are your solution would be more elegant than what i was trying to do. But chances are you might have to rebase and redo the changes to get it to merge now

**Comment by weiw11** [comment]
I'm almost done with the merge but I'm not sure if you want the main input group to be 2 lines or 1 for desktop size.

image

I think it looks a lot better since everything's not squished. Otherwise we would have to adjust the max width to fit the input box comfortably, but it'll still squish some of the inputs when resizing the width.

Previous 1920 width:
image

Previous >1200 width:
image

Edit:
The same goes for the advanced options as well. I think 2 rows would be better UI/UX design wise.

How it looks with all the commits:

**Review by Silberdrachi — APPROVED** [review]

**Comment by Silberdrachi** [comment]
Thanks, this turned out real well. UI Design is def not my forte, and this is what i was looking for.

**Comment by weiw11** [comment]
Np, I actually wanted to thank you for maintaining this as well as it's been extremely useful. So I'm glad I was able to help out a bit.

**Pull request merged**
